/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author diego
 */
public class Interfaz extends javax.swing.JFrame {

    // Interación con el nuevo boton de salida
    int xMouse, yMouse;
    
    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PanelDeFondo = new javax.swing.JPanel();
        Diagonal1 = new javax.swing.JLabel();
        ImagenDeFondo = new javax.swing.JLabel();
        Menú = new javax.swing.JLabel();
        Repositorio = new javax.swing.JButton();
        Alquiler = new javax.swing.JButton();
        Moderador = new javax.swing.JButton();
        PanelExit = new javax.swing.JPanel();
        PanelExit1 = new javax.swing.JPanel();
        BotonExit = new javax.swing.JLabel();
        Diagonal = new javax.swing.JLabel();
        Diagonal2 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineas diagonales.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        PanelDeFondo.setBackground(new java.awt.Color(255, 255, 255));
        PanelDeFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Diagonal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LineasDiagonales1.png"))); // NOI18N
        PanelDeFondo.add(Diagonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, -20, 140, 130));

        ImagenDeFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen1.jpg"))); // NOI18N
        PanelDeFondo.add(ImagenDeFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 440));

        Menú.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenMenu.png"))); // NOI18N
        PanelDeFondo.add(Menú, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 410, 230));

        Repositorio.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Repositorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconPeli.png"))); // NOI18N
        Repositorio.setText("REPOSITORIO");
        Repositorio.setBorderPainted(false);
        Repositorio.setContentAreaFilled(false);
        Repositorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Repositorio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconPeli.png"))); // NOI18N
        Repositorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconPeli1.png"))); // NOI18N
        Repositorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Repositorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepositorioMouseClicked(evt);
            }
        });
        Repositorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepositorioActionPerformed(evt);
            }
        });
        PanelDeFondo.add(Repositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 150, 180));

        Alquiler.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Alquiler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ticket.png"))); // NOI18N
        Alquiler.setText("ALQUILER");
        Alquiler.setBorderPainted(false);
        Alquiler.setContentAreaFilled(false);
        Alquiler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Alquiler.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ticket.png"))); // NOI18N
        Alquiler.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ticket1.png"))); // NOI18N
        Alquiler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Alquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlquilerMouseClicked(evt);
            }
        });
        Alquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlquilerActionPerformed(evt);
            }
        });
        PanelDeFondo.add(Alquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 150, 160));

        Moderador.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        Moderador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acceso1.png"))); // NOI18N
        Moderador.setText("MODERADOR");
        Moderador.setBorderPainted(false);
        Moderador.setContentAreaFilled(false);
        Moderador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Moderador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Moderador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acceso1.png"))); // NOI18N
        Moderador.setRolloverEnabled(true);
        Moderador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Acceso.png"))); // NOI18N
        Moderador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Moderador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeradorActionPerformed(evt);
            }
        });
        PanelDeFondo.add(Moderador, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 160, 150));

        PanelExit.setBackground(new java.awt.Color(255, 255, 255));
        PanelExit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelExitMouseDragged(evt);
            }
        });
        PanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelExitMousePressed(evt);
            }
        });

        PanelExit1.setBackground(new java.awt.Color(255, 255, 255));

        BotonExit.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        BotonExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonExit.setText("X");
        BotonExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanelExit1Layout = new javax.swing.GroupLayout(PanelExit1);
        PanelExit1.setLayout(PanelExit1Layout);
        PanelExit1Layout.setHorizontalGroup(
            PanelExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelExit1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelExit1Layout.setVerticalGroup(
            PanelExit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelExit1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelExitLayout = new javax.swing.GroupLayout(PanelExit);
        PanelExit.setLayout(PanelExitLayout);
        PanelExitLayout.setHorizontalGroup(
            PanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelExitLayout.createSequentialGroup()
                .addContainerGap(640, Short.MAX_VALUE)
                .addComponent(PanelExit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelExitLayout.setVerticalGroup(
            PanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelExit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        PanelDeFondo.add(PanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        Diagonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineas diagonales.png"))); // NOI18N
        PanelDeFondo.add(Diagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 150));

        Diagonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LineasDiagonales2.png"))); // NOI18N
        PanelDeFondo.add(Diagonal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 220, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDeFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlquilerActionPerformed

    private void RepositorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepositorioMouseClicked
        //***** CODIGO ******//
        
        this.dispose(); // para que se cierra cuando la otra se abra
        
    }//GEN-LAST:event_RepositorioMouseClicked

    private void PanelExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelExitMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_PanelExitMousePressed

    private void PanelExitMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelExitMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_PanelExitMouseDragged

    private void BotonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonExitMouseClicked

    private void BotonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseEntered
        PanelExit1.setBackground(Color.red);
        BotonExit.setForeground(Color.white);
    }//GEN-LAST:event_BotonExitMouseEntered

    private void BotonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonExitMouseExited
        PanelExit1.setBackground(Color.white);
        BotonExit.setForeground(Color.black);
    }//GEN-LAST:event_BotonExitMouseExited

    private void RepositorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepositorioActionPerformed
        Catálogo disponibles = new Catálogo();
        disponibles.setVisible(true);
    }//GEN-LAST:event_RepositorioActionPerformed

    private void AlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlquilerMouseClicked
        //** CODIGO
        Cliente ventana2 = new Cliente();
        ventana2.setVisible(true);
        this.dispose(); // para que se cierra cuando la otra se abra
    }//GEN-LAST:event_AlquilerMouseClicked

    private void ModeradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeradorActionPerformed
        Acceso ventana3 = new Acceso();
        ventana3.setVisible(true);
        this.dispose(); // para que se cierra cuando la otra se abra
    }//GEN-LAST:event_ModeradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alquiler;
    private javax.swing.JLabel BotonExit;
    private javax.swing.JLabel Diagonal;
    private javax.swing.JLabel Diagonal1;
    private javax.swing.JLabel Diagonal2;
    private javax.swing.JLabel ImagenDeFondo;
    private javax.swing.JLabel Menú;
    private javax.swing.JButton Moderador;
    private javax.swing.JPanel PanelDeFondo;
    private javax.swing.JPanel PanelExit;
    private javax.swing.JPanel PanelExit1;
    private javax.swing.JButton Repositorio;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
